### ISSUE TITLE
locale

### ISSUE THREAD

**Issue by yorickvP** [OVChip/ovchipapi-node#2]
The app makes some requests with a `locale: 'nl-NL'` parameter. Is this important, does it affect stuff?

**Comment by Bart0110** [comment]
The locale header shouldn't make any difference. If it isn't passed along the data would return just fine. If you change it to another language it doesn't affect the results either so I think that we can leave it as it is.

**Comment by yorickvP** [comment]
I was thinking maybe it would change `transactionName` from "Check-uit" to "Check-out" (or maybe it will in the future).
